#pragma once

#include "lite_scancode.h"

#define LITE_SCANCODE_MASK              (1<<30)
#define LITE_SCANCODE_TO_KEYCODE(X)     ((X) | LITE_SCANCODE_MASK)

typedef enum
{
    LiteKeyCode_UNKNOWN = 0,

    LiteKeyCode_RETURN = '\r',
    LiteKeyCode_ESCAPE = '\x1B',
    LiteKeyCode_BACKSPACE = '\b',
    LiteKeyCode_TAB = '\t',
    LiteKeyCode_SPACE = ' ',
    LiteKeyCode_EXCLAIM = '!',
    LiteKeyCode_QUOTEDBL = '"',
    LiteKeyCode_HASH = '#',
    LiteKeyCode_PERCENT = '%',
    LiteKeyCode_DOLLAR = '$',
    LiteKeyCode_AMPERSAND = '&',
    LiteKeyCode_QUOTE = '\'',
    LiteKeyCode_LEFTPAREN = '(',
    LiteKeyCode_RIGHTPAREN = ')',
    LiteKeyCode_ASTERISK = '*',
    LiteKeyCode_PLUS = '+',
    LiteKeyCode_COMMA = ',',
    LiteKeyCode_MINUS = '-',
    LiteKeyCode_PERIOD = '.',
    LiteKeyCode_SLASH = '/',
    LiteKeyCode_0 = '0',
    LiteKeyCode_1 = '1',
    LiteKeyCode_2 = '2',
    LiteKeyCode_3 = '3',
    LiteKeyCode_4 = '4',
    LiteKeyCode_5 = '5',
    LiteKeyCode_6 = '6',
    LiteKeyCode_7 = '7',
    LiteKeyCode_8 = '8',
    LiteKeyCode_9 = '9',
    LiteKeyCode_COLON = ':',
    LiteKeyCode_SEMICOLON = ';',
    LiteKeyCode_LESS = '<',
    LiteKeyCode_EQUALS = '=',
    LiteKeyCode_GREATER = '>',
    LiteKeyCode_QUESTION = '?',
    LiteKeyCode_AT = '@',

    /*
       Skip uppercase letters
     */

    LiteKeyCode_LEFTBRACKET = '[',
    LiteKeyCode_BACKSLASH = '\\',
    LiteKeyCode_RIGHTBRACKET = ']',
    LiteKeyCode_CARET = '^',
    LiteKeyCode_UNDERSCORE = '_',
    LiteKeyCode_BACKQUOTE = '`',
    LiteKeyCode_a = 'a',
    LiteKeyCode_b = 'b',
    LiteKeyCode_c = 'c',
    LiteKeyCode_d = 'd',
    LiteKeyCode_e = 'e',
    LiteKeyCode_f = 'f',
    LiteKeyCode_g = 'g',
    LiteKeyCode_h = 'h',
    LiteKeyCode_i = 'i',
    LiteKeyCode_j = 'j',
    LiteKeyCode_k = 'k',
    LiteKeyCode_l = 'l',
    LiteKeyCode_m = 'm',
    LiteKeyCode_n = 'n',
    LiteKeyCode_o = 'o',
    LiteKeyCode_p = 'p',
    LiteKeyCode_q = 'q',
    LiteKeyCode_r = 'r',
    LiteKeyCode_s = 's',
    LiteKeyCode_t = 't',
    LiteKeyCode_u = 'u',
    LiteKeyCode_v = 'v',
    LiteKeyCode_w = 'w',
    LiteKeyCode_x = 'x',
    LiteKeyCode_y = 'y',
    LiteKeyCode_z = 'z',

    LiteKeyCode_CAPSLOCK = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_CAPSLOCK),

    LiteKeyCode_F1 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F1),
    LiteKeyCode_F2 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F2),
    LiteKeyCode_F3 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F3),
    LiteKeyCode_F4 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F4),
    LiteKeyCode_F5 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F5),
    LiteKeyCode_F6 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F6),
    LiteKeyCode_F7 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F7),
    LiteKeyCode_F8 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F8),
    LiteKeyCode_F9 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F9),
    LiteKeyCode_F10 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F10),
    LiteKeyCode_F11 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F11),
    LiteKeyCode_F12 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F12),

    LiteKeyCode_PRINTSCREEN = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_PRINTSCREEN),
    LiteKeyCode_SCROLLLOCK = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_SCROLLLOCK),
    LiteKeyCode_PAUSE = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_PAUSE),
    LiteKeyCode_INSERT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_INSERT),
    LiteKeyCode_HOME = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_HOME),
    LiteKeyCode_PAGEUP = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_PAGEUP),
    LiteKeyCode_DELETE = '\x7F',
    LiteKeyCode_END = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_END),
    LiteKeyCode_PAGEDOWN = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_PAGEDOWN),
    LiteKeyCode_RIGHT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_RIGHT),
    LiteKeyCode_LEFT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_LEFT),
    LiteKeyCode_DOWN = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_DOWN),
    LiteKeyCode_UP = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_UP),

    LiteKeyCode_NUMLOCKCLEAR = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_NUMLOCKCLEAR),
    LiteKeyCode_KP_DIVIDE = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_DIVIDE),
    LiteKeyCode_KP_MULTIPLY = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_MULTIPLY),
    LiteKeyCode_KP_MINUS = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_MINUS),
    LiteKeyCode_KP_PLUS = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_PLUS),
    LiteKeyCode_KP_ENTER = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_ENTER),
    LiteKeyCode_KP_1 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_1),
    LiteKeyCode_KP_2 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_2),
    LiteKeyCode_KP_3 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_3),
    LiteKeyCode_KP_4 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_4),
    LiteKeyCode_KP_5 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_5),
    LiteKeyCode_KP_6 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_6),
    LiteKeyCode_KP_7 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_7),
    LiteKeyCode_KP_8 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_8),
    LiteKeyCode_KP_9 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_9),
    LiteKeyCode_KP_0 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_0),
    LiteKeyCode_KP_PERIOD = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_PERIOD),

    LiteKeyCode_APPLICATION = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_APPLICATION),
    LiteKeyCode_POWER = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_POWER),
    LiteKeyCode_KP_EQUALS = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_EQUALS),
    LiteKeyCode_F13 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F13),
    LiteKeyCode_F14 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F14),
    LiteKeyCode_F15 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F15),
    LiteKeyCode_F16 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F16),
    LiteKeyCode_F17 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F17),
    LiteKeyCode_F18 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F18),
    LiteKeyCode_F19 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F19),
    LiteKeyCode_F20 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F20),
    LiteKeyCode_F21 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F21),
    LiteKeyCode_F22 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F22),
    LiteKeyCode_F23 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F23),
    LiteKeyCode_F24 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_F24),
    LiteKeyCode_EXECUTE = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_EXECUTE),
    LiteKeyCode_HELP = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_HELP),
    LiteKeyCode_MENU = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_MENU),
    LiteKeyCode_SELECT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_SELECT),
    LiteKeyCode_STOP = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_STOP),
    LiteKeyCode_AGAIN = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AGAIN),
    LiteKeyCode_UNDO = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_UNDO),
    LiteKeyCode_CUT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_CUT),
    LiteKeyCode_COPY = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_COPY),
    LiteKeyCode_PASTE = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_PASTE),
    LiteKeyCode_FIND = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_FIND),
    LiteKeyCode_MUTE = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_MUTE),
    LiteKeyCode_VOLUMEUP = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_VOLUMEUP),
    LiteKeyCode_VOLUMEDOWN = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_VOLUMEDOWN),
    LiteKeyCode_KP_COMMA = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_COMMA),
    LiteKeyCode_KP_EQUALSAS400 =
        LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_EQUALSAS400),

    LiteKeyCode_ALTERASE = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_ALTERASE),
    LiteKeyCode_SYSREQ = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_SYSREQ),
    LiteKeyCode_CANCEL = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_CANCEL),
    LiteKeyCode_CLEAR = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_CLEAR),
    LiteKeyCode_PRIOR = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_PRIOR),
    LiteKeyCode_RETURN2 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_RETURN2),
    LiteKeyCode_SEPARATOR = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_SEPARATOR),
    LiteKeyCode_OUT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_OUT),
    LiteKeyCode_OPER = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_OPER),
    LiteKeyCode_CLEARAGAIN = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_CLEARAGAIN),
    LiteKeyCode_CRSEL = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_CRSEL),
    LiteKeyCode_EXSEL = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_EXSEL),

    LiteKeyCode_KP_00 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_00),
    LiteKeyCode_KP_000 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_000),
    LiteKeyCode_THOUSANDSSEPARATOR =
        LITE_SCANCODE_TO_KEYCODE(LiteScanCode_THOUSANDSSEPARATOR),
    LiteKeyCode_DECIMALSEPARATOR =
        LITE_SCANCODE_TO_KEYCODE(LiteScanCode_DECIMALSEPARATOR),
    LiteKeyCode_CURRENCYUNIT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_CURRENCYUNIT),
    LiteKeyCode_CURRENCYSUBUNIT =
        LITE_SCANCODE_TO_KEYCODE(LiteScanCode_CURRENCYSUBUNIT),
    LiteKeyCode_KP_LEFTPAREN = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_LEFTPAREN),
    LiteKeyCode_KP_RIGHTPAREN = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_RIGHTPAREN),
    LiteKeyCode_KP_LEFTBRACE = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_LEFTBRACE),
    LiteKeyCode_KP_RIGHTBRACE = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_RIGHTBRACE),
    LiteKeyCode_KP_TAB = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_TAB),
    LiteKeyCode_KP_BACKSPACE = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_BACKSPACE),
    LiteKeyCode_KP_A = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_A),
    LiteKeyCode_KP_B = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_B),
    LiteKeyCode_KP_C = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_C),
    LiteKeyCode_KP_D = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_D),
    LiteKeyCode_KP_E = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_E),
    LiteKeyCode_KP_F = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_F),
    LiteKeyCode_KP_XOR = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_XOR),
    LiteKeyCode_KP_POWER = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_POWER),
    LiteKeyCode_KP_PERCENT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_PERCENT),
    LiteKeyCode_KP_LESS = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_LESS),
    LiteKeyCode_KP_GREATER = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_GREATER),
    LiteKeyCode_KP_AMPERSAND = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_AMPERSAND),
    LiteKeyCode_KP_DBLAMPERSAND =
        LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_DBLAMPERSAND),
    LiteKeyCode_KP_VERTICALBAR =
        LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_VERTICALBAR),
    LiteKeyCode_KP_DBLVERTICALBAR =
        LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_DBLVERTICALBAR),
    LiteKeyCode_KP_COLON = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_COLON),
    LiteKeyCode_KP_HASH = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_HASH),
    LiteKeyCode_KP_SPACE = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_SPACE),
    LiteKeyCode_KP_AT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_AT),
    LiteKeyCode_KP_EXCLAM = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_EXCLAM),
    LiteKeyCode_KP_MEMSTORE = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_MEMSTORE),
    LiteKeyCode_KP_MEMRECALL = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_MEMRECALL),
    LiteKeyCode_KP_MEMCLEAR = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_MEMCLEAR),
    LiteKeyCode_KP_MEMADD = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_MEMADD),
    LiteKeyCode_KP_MEMSUBTRACT =
        LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_MEMSUBTRACT),
    LiteKeyCode_KP_MEMMULTIPLY =
        LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_MEMMULTIPLY),
    LiteKeyCode_KP_MEMDIVIDE = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_MEMDIVIDE),
    LiteKeyCode_KP_PLUSMINUS = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_PLUSMINUS),
    LiteKeyCode_KP_CLEAR = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_CLEAR),
    LiteKeyCode_KP_CLEARENTRY = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_CLEARENTRY),
    LiteKeyCode_KP_BINARY = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_BINARY),
    LiteKeyCode_KP_OCTAL = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_OCTAL),
    LiteKeyCode_KP_DECIMAL = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_DECIMAL),
    LiteKeyCode_KP_HEXADECIMAL =
        LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KP_HEXADECIMAL),

    LiteKeyCode_LCTRL = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_LCTRL),
    LiteKeyCode_LSHIFT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_LSHIFT),
    LiteKeyCode_LALT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_LALT),
    LiteKeyCode_LGUI = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_LGUI),
    LiteKeyCode_RCTRL = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_RCTRL),
    LiteKeyCode_RSHIFT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_RSHIFT),
    LiteKeyCode_RALT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_RALT),
    LiteKeyCode_RGUI = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_RGUI),

    LiteKeyCode_MODE = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_MODE),

    LiteKeyCode_AUDIONEXT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AUDIONEXT),
    LiteKeyCode_AUDIOPREV = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AUDIOPREV),
    LiteKeyCode_AUDIOSTOP = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AUDIOSTOP),
    LiteKeyCode_AUDIOPLAY = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AUDIOPLAY),
    LiteKeyCode_AUDIOMUTE = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AUDIOMUTE),
    LiteKeyCode_MEDIASELECT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_MEDIASELECT),
    LiteKeyCode_WWW = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_WWW),
    LiteKeyCode_MAIL = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_MAIL),
    LiteKeyCode_CALCULATOR = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_CALCULATOR),
    LiteKeyCode_COMPUTER = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_COMPUTER),
    LiteKeyCode_AC_SEARCH = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AC_SEARCH),
    LiteKeyCode_AC_HOME = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AC_HOME),
    LiteKeyCode_AC_BACK = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AC_BACK),
    LiteKeyCode_AC_FORWARD = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AC_FORWARD),
    LiteKeyCode_AC_STOP = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AC_STOP),
    LiteKeyCode_AC_REFRESH = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AC_REFRESH),
    LiteKeyCode_AC_BOOKMARKS = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AC_BOOKMARKS),

    LiteKeyCode_BRIGHTNESSDOWN =
        LITE_SCANCODE_TO_KEYCODE(LiteScanCode_BRIGHTNESSDOWN),
    LiteKeyCode_BRIGHTNESSUP = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_BRIGHTNESSUP),
    LiteKeyCode_DISPLAYSWITCH = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_DISPLAYSWITCH),
    LiteKeyCode_KBDILLUMTOGGLE =
        LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KBDILLUMTOGGLE),
    LiteKeyCode_KBDILLUMDOWN = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KBDILLUMDOWN),
    LiteKeyCode_KBDILLUMUP = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_KBDILLUMUP),
    LiteKeyCode_EJECT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_EJECT),
    LiteKeyCode_SLEEP = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_SLEEP),
    LiteKeyCode_APP1 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_APP1),
    LiteKeyCode_APP2 = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_APP2),

    LiteKeyCode_AUDIOREWIND = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AUDIOREWIND),
    LiteKeyCode_AUDIOFASTFORWARD = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_AUDIOFASTFORWARD),

    LiteKeyCode_SOFTLEFT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_SOFTLEFT),
    LiteKeyCode_SOFTRIGHT = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_SOFTRIGHT),
    LiteKeyCode_CALL = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_CALL),
    LiteKeyCode_ENDCALL = LITE_SCANCODE_TO_KEYCODE(LiteScanCode_ENDCALL)
} LiteKeyCode;

/**
 * Enumeration of valid key mods (possibly OR'd together).
 */
typedef enum
{
    SDL_KMOD_NONE = 0x0000,
    SDL_KMOD_LSHIFT = 0x0001,
    SDL_KMOD_RSHIFT = 0x0002,
    SDL_KMOD_LCTRL = 0x0040,
    SDL_KMOD_RCTRL = 0x0080,
    SDL_KMOD_LALT = 0x0100,
    SDL_KMOD_RALT = 0x0200,
    SDL_KMOD_LGUI = 0x0400,
    SDL_KMOD_RGUI = 0x0800,
    SDL_KMOD_NUM = 0x1000,
    SDL_KMOD_CAPS = 0x2000,
    SDL_KMOD_MODE = 0x4000,
    SDL_KMOD_SCROLL = 0x8000,

    SDL_KMOD_CTRL = SDL_KMOD_LCTRL | SDL_KMOD_RCTRL,
    SDL_KMOD_SHIFT = SDL_KMOD_LSHIFT | SDL_KMOD_RSHIFT,
    SDL_KMOD_ALT = SDL_KMOD_LALT | SDL_KMOD_RALT,
    SDL_KMOD_GUI = SDL_KMOD_LGUI | SDL_KMOD_RGUI,

    SDL_KMOD_RESERVED = SDL_KMOD_SCROLL /* This is for source-level compatibility with SDL 2.0.0. */
} LiteKeyMod;

//! EOF

